# :vcs: Hg
# :vcs: Git
:vcs: Svn

# :language: csharp
# :language: ruby
:language: java

#only works for java
:classpath: /workflow/trunk/editor/src/main/java/
        
:projects:
    # - admin
    # - admin-cli
    # - crm
    # - framework
    # - mytaxes
    # - questionnaire
    # - irefactoring
    - editor
