# :vcs: Hg
# :vcs: Git
# :vcs: Clearcase
:vcs: Svn

# :language: csharp
# :language: ruby
# :language: c++
:language: java

#only works for java
:classpath: /workflow/trunk/editor/src/main/java/
        
:projects:
    # - framework
    # - mytaxes
    # - questionnaire
    # - irefactoring
    - example
