:name: CWP
# :vcs: Svn
:vcs: Hg
# :language: java
:language: csharp
:projects:
    - admin
    - admin-cli
    - crm
    - framework
    - mytaxes
    - questionnaire
    - questionnaire-admin-cqs
    - questionnaire-admin-gde
    - questionnaire-admin-integration