# :vcs: Svn
:vcs: Hg
# :vcs: Git
# :vcs: Clearcase

# :language: java
:language: csharp
# :language: ruby
# :language: c++


:projects:
    - admin
    - admin-cli
    - crm
    - framework
    - mytaxes
    - questionnaire